# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PPI-Tester
version:      0.04
version_from: lib/PPI/Tester.pm
installdirs:  site
requires:
    PPI:                           0.814
    Test::More:                    0
    Wx:                            0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
