name: PPI-Tester
version: 0.06
abstract: A wxPerl-based interactive PPI debugger/tester
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
requires:
  perl: 5.005
  PPI: 0.840
  Wx: 0.19
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
